package com.entity;

// Generated 2020-7-22 10:29:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActEvtLog generated by hbm2java
 */
@Entity
@Table(name = "ACT_EVT_LOG", catalog = "sjtu_train")
public class ActEvtLog implements java.io.Serializable {

	private Long logNr;
	private String type;
	private String procDefId;
	private String procInstId;
	private String executionId;
	private String taskId;
	private Date timeStamp;
	private String userId;
	private byte[] data;
	private String lockOwner;
	private Date lockTime;
	private Byte isProcessed;

	public ActEvtLog() {
	}

	public ActEvtLog(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	public ActEvtLog(String type, String procDefId, String procInstId,
			String executionId, String taskId, Date timeStamp, String userId,
			byte[] data, String lockOwner, Date lockTime, Byte isProcessed) {
		this.type = type;
		this.procDefId = procDefId;
		this.procInstId = procInstId;
		this.executionId = executionId;
		this.taskId = taskId;
		this.timeStamp = timeStamp;
		this.userId = userId;
		this.data = data;
		this.lockOwner = lockOwner;
		this.lockTime = lockTime;
		this.isProcessed = isProcessed;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LOG_NR_", unique = true, nullable = false)
	public Long getLogNr() {
		return this.logNr;
	}

	public void setLogNr(Long logNr) {
		this.logNr = logNr;
	}

	@Column(name = "TYPE_", length = 64)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "PROC_DEF_ID_", length = 64)
	public String getProcDefId() {
		return this.procDefId;
	}

	public void setProcDefId(String procDefId) {
		this.procDefId = procDefId;
	}

	@Column(name = "PROC_INST_ID_", length = 64)
	public String getProcInstId() {
		return this.procInstId;
	}

	public void setProcInstId(String procInstId) {
		this.procInstId = procInstId;
	}

	@Column(name = "EXECUTION_ID_", length = 64)
	public String getExecutionId() {
		return this.executionId;
	}

	public void setExecutionId(String executionId) {
		this.executionId = executionId;
	}

	@Column(name = "TASK_ID_", length = 64)
	public String getTaskId() {
		return this.taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIME_STAMP_", nullable = false, length = 19)
	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	@Column(name = "USER_ID_")
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "DATA_")
	public byte[] getData() {
		return this.data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

	@Column(name = "LOCK_OWNER_")
	public String getLockOwner() {
		return this.lockOwner;
	}

	public void setLockOwner(String lockOwner) {
		this.lockOwner = lockOwner;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LOCK_TIME_", length = 19)
	public Date getLockTime() {
		return this.lockTime;
	}

	public void setLockTime(Date lockTime) {
		this.lockTime = lockTime;
	}

	@Column(name = "IS_PROCESSED_")
	public Byte getIsProcessed() {
		return this.isProcessed;
	}

	public void setIsProcessed(Byte isProcessed) {
		this.isProcessed = isProcessed;
	}

}
