package com.entity;

// Generated 2020-7-22 10:29:49 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ActGeBytearray generated by hbm2java
 */
@Entity
@Table(name = "ACT_GE_BYTEARRAY", catalog = "sjtu_train")
public class ActGeBytearray implements java.io.Serializable {

	private String id;
	private ActReDeployment actReDeployment;
	private Integer rev;
	private String name;
	private byte[] bytes;
	private Byte generated;
	private Set<ActRuJob> actRuJobs = new HashSet<ActRuJob>(0);
	private Set<ActRuSuspendedJob> actRuSuspendedJobs = new HashSet<ActRuSuspendedJob>(
			0);
	private Set<ActReModel> actReModelsForEditorSourceValueId = new HashSet<ActReModel>(
			0);
	private Set<ActReModel> actReModelsForEditorSourceExtraValueId = new HashSet<ActReModel>(
			0);
	private Set<ActRuDeadletterJob> actRuDeadletterJobs = new HashSet<ActRuDeadletterJob>(
			0);
	private Set<ActRuTimerJob> actRuTimerJobs = new HashSet<ActRuTimerJob>(0);
	private Set<ActProcdefInfo> actProcdefInfos = new HashSet<ActProcdefInfo>(0);
	private Set<ActRuVariable> actRuVariables = new HashSet<ActRuVariable>(0);

	public ActGeBytearray() {
	}

	public ActGeBytearray(String id) {
		this.id = id;
	}

	public ActGeBytearray(String id, ActReDeployment actReDeployment,
			Integer rev, String name, byte[] bytes, Byte generated,
			Set<ActRuJob> actRuJobs, Set<ActRuSuspendedJob> actRuSuspendedJobs,
			Set<ActReModel> actReModelsForEditorSourceValueId,
			Set<ActReModel> actReModelsForEditorSourceExtraValueId,
			Set<ActRuDeadletterJob> actRuDeadletterJobs,
			Set<ActRuTimerJob> actRuTimerJobs,
			Set<ActProcdefInfo> actProcdefInfos,
			Set<ActRuVariable> actRuVariables) {
		this.id = id;
		this.actReDeployment = actReDeployment;
		this.rev = rev;
		this.name = name;
		this.bytes = bytes;
		this.generated = generated;
		this.actRuJobs = actRuJobs;
		this.actRuSuspendedJobs = actRuSuspendedJobs;
		this.actReModelsForEditorSourceValueId = actReModelsForEditorSourceValueId;
		this.actReModelsForEditorSourceExtraValueId = actReModelsForEditorSourceExtraValueId;
		this.actRuDeadletterJobs = actRuDeadletterJobs;
		this.actRuTimerJobs = actRuTimerJobs;
		this.actProcdefInfos = actProcdefInfos;
		this.actRuVariables = actRuVariables;
	}

	@Id
	@Column(name = "ID_", unique = true, nullable = false, length = 64)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEPLOYMENT_ID_")
	public ActReDeployment getActReDeployment() {
		return this.actReDeployment;
	}

	public void setActReDeployment(ActReDeployment actReDeployment) {
		this.actReDeployment = actReDeployment;
	}

	@Column(name = "REV_")
	public Integer getRev() {
		return this.rev;
	}

	public void setRev(Integer rev) {
		this.rev = rev;
	}

	@Column(name = "NAME_")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "BYTES_")
	public byte[] getBytes() {
		return this.bytes;
	}

	public void setBytes(byte[] bytes) {
		this.bytes = bytes;
	}

	@Column(name = "GENERATED_")
	public Byte getGenerated() {
		return this.generated;
	}

	public void setGenerated(Byte generated) {
		this.generated = generated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actGeBytearray")
	public Set<ActRuJob> getActRuJobs() {
		return this.actRuJobs;
	}

	public void setActRuJobs(Set<ActRuJob> actRuJobs) {
		this.actRuJobs = actRuJobs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actGeBytearray")
	public Set<ActRuSuspendedJob> getActRuSuspendedJobs() {
		return this.actRuSuspendedJobs;
	}

	public void setActRuSuspendedJobs(Set<ActRuSuspendedJob> actRuSuspendedJobs) {
		this.actRuSuspendedJobs = actRuSuspendedJobs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actGeBytearrayByEditorSourceValueId")
	public Set<ActReModel> getActReModelsForEditorSourceValueId() {
		return this.actReModelsForEditorSourceValueId;
	}

	public void setActReModelsForEditorSourceValueId(
			Set<ActReModel> actReModelsForEditorSourceValueId) {
		this.actReModelsForEditorSourceValueId = actReModelsForEditorSourceValueId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actGeBytearrayByEditorSourceExtraValueId")
	public Set<ActReModel> getActReModelsForEditorSourceExtraValueId() {
		return this.actReModelsForEditorSourceExtraValueId;
	}

	public void setActReModelsForEditorSourceExtraValueId(
			Set<ActReModel> actReModelsForEditorSourceExtraValueId) {
		this.actReModelsForEditorSourceExtraValueId = actReModelsForEditorSourceExtraValueId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actGeBytearray")
	public Set<ActRuDeadletterJob> getActRuDeadletterJobs() {
		return this.actRuDeadletterJobs;
	}

	public void setActRuDeadletterJobs(
			Set<ActRuDeadletterJob> actRuDeadletterJobs) {
		this.actRuDeadletterJobs = actRuDeadletterJobs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actGeBytearray")
	public Set<ActRuTimerJob> getActRuTimerJobs() {
		return this.actRuTimerJobs;
	}

	public void setActRuTimerJobs(Set<ActRuTimerJob> actRuTimerJobs) {
		this.actRuTimerJobs = actRuTimerJobs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actGeBytearray")
	public Set<ActProcdefInfo> getActProcdefInfos() {
		return this.actProcdefInfos;
	}

	public void setActProcdefInfos(Set<ActProcdefInfo> actProcdefInfos) {
		this.actProcdefInfos = actProcdefInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actGeBytearray")
	public Set<ActRuVariable> getActRuVariables() {
		return this.actRuVariables;
	}

	public void setActRuVariables(Set<ActRuVariable> actRuVariables) {
		this.actRuVariables = actRuVariables;
	}

}
