package com.entity;

// Generated 2020-7-22 10:29:49 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ActProcdefInfo generated by hbm2java
 */
@Entity
@Table(name = "ACT_PROCDEF_INFO", catalog = "sast_train", uniqueConstraints = @UniqueConstraint(columnNames = "PROC_DEF_ID_"))
public class ActProcdefInfo implements java.io.Serializable {

	private String id;
	private ActReProcdef actReProcdef;
	private ActGeBytearray actGeBytearray;
	private Integer rev;

	public ActProcdefInfo() {
	}

	public ActProcdefInfo(String id, ActReProcdef actReProcdef) {
		this.id = id;
		this.actReProcdef = actReProcdef;
	}

	public ActProcdefInfo(String id, ActReProcdef actReProcdef,
			ActGeBytearray actGeBytearray, Integer rev) {
		this.id = id;
		this.actReProcdef = actReProcdef;
		this.actGeBytearray = actGeBytearray;
		this.rev = rev;
	}

	@Id
	@Column(name = "ID_", unique = true, nullable = false, length = 64)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROC_DEF_ID_", unique = true, nullable = false)
	public ActReProcdef getActReProcdef() {
		return this.actReProcdef;
	}

	public void setActReProcdef(ActReProcdef actReProcdef) {
		this.actReProcdef = actReProcdef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INFO_JSON_ID_")
	public ActGeBytearray getActGeBytearray() {
		return this.actGeBytearray;
	}

	public void setActGeBytearray(ActGeBytearray actGeBytearray) {
		this.actGeBytearray = actGeBytearray;
	}

	@Column(name = "REV_")
	public Integer getRev() {
		return this.rev;
	}

	public void setRev(Integer rev) {
		this.rev = rev;
	}

}
