package com.entity;

// Generated 2020-7-22 10:29:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActReModel generated by hbm2java
 */
@Entity
@Table(name = "ACT_RE_MODEL", catalog = "sjtu_train")
public class ActReModel implements java.io.Serializable {

	private String id;
	private ActGeBytearray actGeBytearrayByEditorSourceValueId;
	private ActReDeployment actReDeployment;
	private ActGeBytearray actGeBytearrayByEditorSourceExtraValueId;
	private Integer rev;
	private String name;
	private String key;
	private String category;
	private Date createTime;
	private Date lastUpdateTime;
	private Integer version;
	private String metaInfo;
	private String tenantId;

	public ActReModel() {
	}

	public ActReModel(String id) {
		this.id = id;
	}

	public ActReModel(String id,
			ActGeBytearray actGeBytearrayByEditorSourceValueId,
			ActReDeployment actReDeployment,
			ActGeBytearray actGeBytearrayByEditorSourceExtraValueId,
			Integer rev, String name, String key, String category,
			Date createTime, Date lastUpdateTime, Integer version,
			String metaInfo, String tenantId) {
		this.id = id;
		this.actGeBytearrayByEditorSourceValueId = actGeBytearrayByEditorSourceValueId;
		this.actReDeployment = actReDeployment;
		this.actGeBytearrayByEditorSourceExtraValueId = actGeBytearrayByEditorSourceExtraValueId;
		this.rev = rev;
		this.name = name;
		this.key = key;
		this.category = category;
		this.createTime = createTime;
		this.lastUpdateTime = lastUpdateTime;
		this.version = version;
		this.metaInfo = metaInfo;
		this.tenantId = tenantId;
	}

	@Id
	@Column(name = "ID_", unique = true, nullable = false, length = 64)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EDITOR_SOURCE_VALUE_ID_")
	public ActGeBytearray getActGeBytearrayByEditorSourceValueId() {
		return this.actGeBytearrayByEditorSourceValueId;
	}

	public void setActGeBytearrayByEditorSourceValueId(
			ActGeBytearray actGeBytearrayByEditorSourceValueId) {
		this.actGeBytearrayByEditorSourceValueId = actGeBytearrayByEditorSourceValueId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEPLOYMENT_ID_")
	public ActReDeployment getActReDeployment() {
		return this.actReDeployment;
	}

	public void setActReDeployment(ActReDeployment actReDeployment) {
		this.actReDeployment = actReDeployment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EDITOR_SOURCE_EXTRA_VALUE_ID_")
	public ActGeBytearray getActGeBytearrayByEditorSourceExtraValueId() {
		return this.actGeBytearrayByEditorSourceExtraValueId;
	}

	public void setActGeBytearrayByEditorSourceExtraValueId(
			ActGeBytearray actGeBytearrayByEditorSourceExtraValueId) {
		this.actGeBytearrayByEditorSourceExtraValueId = actGeBytearrayByEditorSourceExtraValueId;
	}

	@Column(name = "REV_")
	public Integer getRev() {
		return this.rev;
	}

	public void setRev(Integer rev) {
		this.rev = rev;
	}

	@Column(name = "NAME_")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "KEY_")
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "CATEGORY_")
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME_", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE_TIME_", length = 19)
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	@Column(name = "VERSION_")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "META_INFO_", length = 4000)
	public String getMetaInfo() {
		return this.metaInfo;
	}

	public void setMetaInfo(String metaInfo) {
		this.metaInfo = metaInfo;
	}

	@Column(name = "TENANT_ID_")
	public String getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

}
