package com.entity;

// Generated 2020-7-22 10:29:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActRuDeadletterJob generated by hbm2java
 */
@Entity
@Table(name = "ACT_RU_DEADLETTER_JOB", catalog = "sast_train")
public class ActRuDeadletterJob implements java.io.Serializable {

	private String id;
	private ActRuExecution actRuExecutionByProcessInstanceId;
	private ActReProcdef actReProcdef;
	private ActRuExecution actRuExecutionByExecutionId;
	private ActGeBytearray actGeBytearray;
	private Integer rev;
	private String type;
	private Boolean exclusive;
	private String exceptionMsg;
	private Date duedate;
	private String repeat;
	private String handlerType;
	private String handlerCfg;
	private String tenantId;

	public ActRuDeadletterJob() {
	}

	public ActRuDeadletterJob(String id, String type) {
		this.id = id;
		this.type = type;
	}

	public ActRuDeadletterJob(String id,
			ActRuExecution actRuExecutionByProcessInstanceId,
			ActReProcdef actReProcdef,
			ActRuExecution actRuExecutionByExecutionId,
			ActGeBytearray actGeBytearray, Integer rev, String type,
			Boolean exclusive, String exceptionMsg, Date duedate,
			String repeat, String handlerType, String handlerCfg,
			String tenantId) {
		this.id = id;
		this.actRuExecutionByProcessInstanceId = actRuExecutionByProcessInstanceId;
		this.actReProcdef = actReProcdef;
		this.actRuExecutionByExecutionId = actRuExecutionByExecutionId;
		this.actGeBytearray = actGeBytearray;
		this.rev = rev;
		this.type = type;
		this.exclusive = exclusive;
		this.exceptionMsg = exceptionMsg;
		this.duedate = duedate;
		this.repeat = repeat;
		this.handlerType = handlerType;
		this.handlerCfg = handlerCfg;
		this.tenantId = tenantId;
	}

	@Id
	@Column(name = "ID_", unique = true, nullable = false, length = 64)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROCESS_INSTANCE_ID_")
	public ActRuExecution getActRuExecutionByProcessInstanceId() {
		return this.actRuExecutionByProcessInstanceId;
	}

	public void setActRuExecutionByProcessInstanceId(
			ActRuExecution actRuExecutionByProcessInstanceId) {
		this.actRuExecutionByProcessInstanceId = actRuExecutionByProcessInstanceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROC_DEF_ID_")
	public ActReProcdef getActReProcdef() {
		return this.actReProcdef;
	}

	public void setActReProcdef(ActReProcdef actReProcdef) {
		this.actReProcdef = actReProcdef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXECUTION_ID_")
	public ActRuExecution getActRuExecutionByExecutionId() {
		return this.actRuExecutionByExecutionId;
	}

	public void setActRuExecutionByExecutionId(
			ActRuExecution actRuExecutionByExecutionId) {
		this.actRuExecutionByExecutionId = actRuExecutionByExecutionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXCEPTION_STACK_ID_")
	public ActGeBytearray getActGeBytearray() {
		return this.actGeBytearray;
	}

	public void setActGeBytearray(ActGeBytearray actGeBytearray) {
		this.actGeBytearray = actGeBytearray;
	}

	@Column(name = "REV_")
	public Integer getRev() {
		return this.rev;
	}

	public void setRev(Integer rev) {
		this.rev = rev;
	}

	@Column(name = "TYPE_", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "EXCLUSIVE_")
	public Boolean getExclusive() {
		return this.exclusive;
	}

	public void setExclusive(Boolean exclusive) {
		this.exclusive = exclusive;
	}

	@Column(name = "EXCEPTION_MSG_", length = 4000)
	public String getExceptionMsg() {
		return this.exceptionMsg;
	}

	public void setExceptionMsg(String exceptionMsg) {
		this.exceptionMsg = exceptionMsg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DUEDATE_", length = 19)
	public Date getDuedate() {
		return this.duedate;
	}

	public void setDuedate(Date duedate) {
		this.duedate = duedate;
	}

	@Column(name = "REPEAT_")
	public String getRepeat() {
		return this.repeat;
	}

	public void setRepeat(String repeat) {
		this.repeat = repeat;
	}

	@Column(name = "HANDLER_TYPE_")
	public String getHandlerType() {
		return this.handlerType;
	}

	public void setHandlerType(String handlerType) {
		this.handlerType = handlerType;
	}

	@Column(name = "HANDLER_CFG_", length = 4000)
	public String getHandlerCfg() {
		return this.handlerCfg;
	}

	public void setHandlerCfg(String handlerCfg) {
		this.handlerCfg = handlerCfg;
	}

	@Column(name = "TENANT_ID_")
	public String getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

}
