package com.entity;

// Generated 2020-7-22 10:29:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActReDeployment generated by hbm2java
 */
@Entity
@Table(name = "ACT_RE_DEPLOYMENT", catalog = "sast_train")
public class ActReDeployment implements java.io.Serializable {

	private String id;
	private String name;
	private String category;
	private String key;
	private String tenantId;
	private Date deployTime;
	private String engineVersion;
	private Set<ActGeBytearray> actGeBytearrays = new HashSet<ActGeBytearray>(0);
	private Set<ActReModel> actReModels = new HashSet<ActReModel>(0);

	public ActReDeployment() {
	}

	public ActReDeployment(String id) {
		this.id = id;
	}

	public ActReDeployment(String id, String name, String category, String key,
			String tenantId, Date deployTime, String engineVersion,
			Set<ActGeBytearray> actGeBytearrays, Set<ActReModel> actReModels) {
		this.id = id;
		this.name = name;
		this.category = category;
		this.key = key;
		this.tenantId = tenantId;
		this.deployTime = deployTime;
		this.engineVersion = engineVersion;
		this.actGeBytearrays = actGeBytearrays;
		this.actReModels = actReModels;
	}

	@Id
	@Column(name = "ID_", unique = true, nullable = false, length = 64)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME_")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CATEGORY_")
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "KEY_")
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "TENANT_ID_")
	public String getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DEPLOY_TIME_", length = 19)
	public Date getDeployTime() {
		return this.deployTime;
	}

	public void setDeployTime(Date deployTime) {
		this.deployTime = deployTime;
	}

	@Column(name = "ENGINE_VERSION_")
	public String getEngineVersion() {
		return this.engineVersion;
	}

	public void setEngineVersion(String engineVersion) {
		this.engineVersion = engineVersion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actReDeployment")
	public Set<ActGeBytearray> getActGeBytearrays() {
		return this.actGeBytearrays;
	}

	public void setActGeBytearrays(Set<ActGeBytearray> actGeBytearrays) {
		this.actGeBytearrays = actGeBytearrays;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actReDeployment")
	public Set<ActReModel> getActReModels() {
		return this.actReModels;
	}

	public void setActReModels(Set<ActReModel> actReModels) {
		this.actReModels = actReModels;
	}

}
