package com.entity;

// Generated 2020-7-22 10:29:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActRuIntegration generated by hbm2java
 */
@Entity
@Table(name = "ACT_RU_INTEGRATION", catalog = "sjtu_train")
public class ActRuIntegration implements java.io.Serializable {

	private String id;
	private ActRuExecution actRuExecutionByProcessInstanceId;
	private ActReProcdef actReProcdef;
	private ActRuExecution actRuExecutionByExecutionId;
	private String flowNodeId;
	private Date createdDate;

	public ActRuIntegration() {
	}

	public ActRuIntegration(String id, Date createdDate) {
		this.id = id;
		this.createdDate = createdDate;
	}

	public ActRuIntegration(String id,
			ActRuExecution actRuExecutionByProcessInstanceId,
			ActReProcdef actReProcdef,
			ActRuExecution actRuExecutionByExecutionId, String flowNodeId,
			Date createdDate) {
		this.id = id;
		this.actRuExecutionByProcessInstanceId = actRuExecutionByProcessInstanceId;
		this.actReProcdef = actReProcdef;
		this.actRuExecutionByExecutionId = actRuExecutionByExecutionId;
		this.flowNodeId = flowNodeId;
		this.createdDate = createdDate;
	}

	@Id
	@Column(name = "ID_", unique = true, nullable = false, length = 64)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROCESS_INSTANCE_ID_")
	public ActRuExecution getActRuExecutionByProcessInstanceId() {
		return this.actRuExecutionByProcessInstanceId;
	}

	public void setActRuExecutionByProcessInstanceId(
			ActRuExecution actRuExecutionByProcessInstanceId) {
		this.actRuExecutionByProcessInstanceId = actRuExecutionByProcessInstanceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROC_DEF_ID_")
	public ActReProcdef getActReProcdef() {
		return this.actReProcdef;
	}

	public void setActReProcdef(ActReProcdef actReProcdef) {
		this.actReProcdef = actReProcdef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXECUTION_ID_")
	public ActRuExecution getActRuExecutionByExecutionId() {
		return this.actRuExecutionByExecutionId;
	}

	public void setActRuExecutionByExecutionId(
			ActRuExecution actRuExecutionByExecutionId) {
		this.actRuExecutionByExecutionId = actRuExecutionByExecutionId;
	}

	@Column(name = "FLOW_NODE_ID_", length = 64)
	public String getFlowNodeId() {
		return this.flowNodeId;
	}

	public void setFlowNodeId(String flowNodeId) {
		this.flowNodeId = flowNodeId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE_", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
