package com.entity;

// Generated 2020-7-28 13:41:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SjApplyProject generated by hbm2java
 */
@Entity
@Table(name = "SJ_APPLY_ROLE", catalog = "sjtu_train")
public class ApplyRole implements java.io.Serializable {

	private Integer id;
	private String account;
	private String certifiNo;
	private Integer personType;
	private String roleName;
	private String applyReason;
	private Integer approveResult;
	private String processInstanceId;
	private Date createTime;
	private Date updateTime;

	public ApplyRole() {
	}

	public ApplyRole(String account, String certifiNo, Integer personType,
			String roleName,String applyReason,Integer approveResult, 
			String processInstanceId, Date createTime,Date updateTime) {
		this.account = account;
		this.certifiNo = certifiNo;
		this.personType = personType;
		this.roleName = roleName;
		this.applyReason = applyReason;
		this.approveResult = approveResult;
		this.processInstanceId = processInstanceId;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "account")
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "certifiNo")
	public String getCertifiNo() {
		return certifiNo;
	}

	public void setCertifiNo(String certifiNo) {
		this.certifiNo = certifiNo;
	}

	@Column(name = "personType")
	public Integer getPersonType() {
		return this.personType;
	}

	public void setPersonType(Integer personType) {
		this.personType = personType;
	}

	@Column(name = "roleName")
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}
	
	@Column(name = "applyReason")
	public String getApplyReason() {
		return this.applyReason;
	}

	public void setApplyReason(String applyReason) {
		this.applyReason = applyReason;
	}

	@Column(name = "approveResult")
	public Integer getApproveResult() {
		return this.approveResult;
	}

	public void setApproveResult(Integer approveResult) {
		this.approveResult = approveResult;
	}

	@Column(name = "processInstanceId")
	public String getProcessInstanceId() {
		return this.processInstanceId;
	}

	public void setProcessInstanceId(String processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
