package com.entity;


import static javax.persistence.GenerationType.IDENTITY;

// Generated 2020-9-4 23:05:53 by Hibernate Tools 4.0.1.Final



import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CourseGroup generated by hbm2java
 */
@Entity
@Table(name = "SJ_COURSE_GROUP", catalog = "sjtu_train")
public class CourseGroup implements java.io.Serializable {

	private Integer id;
	private String name;
	private String groupDesc;
	private String teacherTypeIds;
	private String teacherTypeNames;
	private String compilerTypeIds;
	private String compilerTypeNames;
	private String positionIds;
	private String positionNames;
	private String employeeTypeIds;
	private String employeeTypeNames;
	private String organiCode;
	private String createBy;
	private Integer del;
	private Date createTime;
	private Date updateTime;

	public CourseGroup() {
	}

	public CourseGroup(String name, String groupDesc, String teacherTypeIds, String teacherTypeNames,
			String compilerTypeIds,String compilerTypeNames,String positionIds,String positionNames,
			String employeeTypeIds,String employeeTypeNames,String createBy, String organiCode,
			Integer del, Date createTime, Date updateTime) {
		this.name = name;
		this.groupDesc = groupDesc;
		this.teacherTypeIds = teacherTypeIds;
		this.teacherTypeNames=teacherTypeNames;
		this.compilerTypeIds = compilerTypeIds;
		this.compilerTypeNames=compilerTypeNames;
		this.positionIds = positionIds;
		this.positionNames=positionNames;
		this.employeeTypeIds = employeeTypeIds;
		this.employeeTypeNames=employeeTypeNames;
		this.createBy = createBy;
		this.organiCode = organiCode;
		this.del = del;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "GROUP_DESC")
	public String getGroupDesc() {
		return this.groupDesc;
	}

	public void setGroupDesc(String groupDesc) {
		this.groupDesc = groupDesc;
	}

	@Column(name = "TEACHER_TYPE_IDS")
	public String getTeacherTypeIds() {
		return this.teacherTypeIds;
	}

	public void setTeacherTypeIds(String teacherTypeIds) {
		this.teacherTypeIds = teacherTypeIds;
	}
	
	@Column(name = "TEACHER_TYPE_NAMES")
	public String getTeacherTypeNames() {
		return teacherTypeNames;
	}

	public void setTeacherTypeNames(String teacherTypeNames) {
		this.teacherTypeNames = teacherTypeNames;
	}
	
	@Column(name = "COMPILER_TYPE_IDS")
	public String getCompilerTypeIds() {
		return this.compilerTypeIds;
	}

	public void setCompilerTypeIds(String compilerTypeIds) {
		this.compilerTypeIds = compilerTypeIds;
	}
	
	@Column(name = "COMPILER_TYPE_NAMES")
	public String getCompilerTypeNames() {
		return compilerTypeNames;
	}

	public void setCompilerTypeNames(String compilerTypeNames) {
		this.compilerTypeNames = compilerTypeNames;
	}

	@Column(name = "POSITION_IDS")
	public String getPositionIds() {
		return this.positionIds;
	}

	public void setPositionIds(String positionIds) {
		this.positionIds = positionIds;
	}
	
	@Column(name = "POSITION_NAMES")
	public String getPositionNames() {
		return positionNames;
	}

	public void setPositionNames(String positionNames) {
		this.positionNames = positionNames;
	}

	@Column(name = "EMPLOYEE_TYPE_IDS")
	public String getEmployeeTypeIds() {
		return employeeTypeIds;
	}

	public void setEmployeeTypeIds(String employeeTypeIds) {
		this.employeeTypeIds = employeeTypeIds;
	}
	
	@Column(name = "EMPLOYEE_TYPE_NAMES")
	public String getEmployeeTypeNames() {
		return employeeTypeNames;
	}

	public void setEmployeeTypeNames(String employeeTypeNames) {
		this.employeeTypeNames = employeeTypeNames;
	}
	
	@Column(name = "ORGANI_CODE")
	public String getOrganiCode() {
		return organiCode;
	}

	public void setOrganiCode(String organiCode) {
		this.organiCode = organiCode;
	}
	
	@Column(name = "CREATE_BY")
	public String getCreateBy() {
		return createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Column(name = "DEL")
	public Integer getDel() {
		return this.del;
	}

	public void setDel(Integer del) {
		this.del = del;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
