package com.entity;

// Generated 2020-7-22 10:29:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SjCourseSign generated by hbm2java
 */
@Entity
@Table(name = "SJ_COURSE_SIGN", catalog = "sjtu_train", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "ACCOUNT", "COURSE_ID" }),
		@UniqueConstraint(columnNames = { "CERTIFI_NO", "COURSE_ID" }) })
public class CourseSign implements java.io.Serializable {

	private Integer id;
	private String account;
	private String certifiNo;
	private Integer personType;
	private Integer projectId;
	private Integer courseId;
	private Integer signType;
	private Integer checkType;
	private Integer checkStatus;
	private Date scanTime;
	private Integer minuteNumber;
	private Double hourNumber;
	private Integer hourStatus;
	private Integer testScore;
	private Integer testType;
	private Integer testStatus;
	private Integer evaStatus;
	private Integer passStatus;
	private String noPassReason;
	private Integer isInform;
	private Date createTime;
	private Date updateTime;

	public CourseSign() {
	}

	public CourseSign(String account, String certifiNo, Integer personType,
			Integer projectId, Integer courseId, Integer signType,Integer checkType,
			Integer checkStatus,Date scanTime,Integer minuteNumber, Double hourNumber,
			Integer hourStatus, Integer testScore, Integer testType,
			Integer testStatus, Integer evaStatus, Integer passStatus,
			String noPassReason, Integer isInform,Date createTime, Date updateTime) {
		this.account = account;
		this.certifiNo = certifiNo;
		this.personType = personType;
		this.projectId = projectId;
		this.courseId = courseId;
		this.signType = signType;
		this.checkType = checkType;
		this.checkStatus = checkStatus;
		this.scanTime = scanTime;
		this.minuteNumber = minuteNumber;
		this.hourNumber = hourNumber;
		this.hourStatus = hourStatus;
		this.testScore = testScore;
		this.testType = testType;
		this.testStatus = testStatus;
		this.evaStatus = evaStatus;
		this.passStatus = passStatus;
		this.noPassReason = noPassReason;
		this.isInform = isInform;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ACCOUNT")
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "CERTIFI_NO")
	public String getCertifiNo() {
		return certifiNo;
	}

	public void setCertifiNo(String certifiNo) {
		this.certifiNo = certifiNo;
	}

	@Column(name = "PERSON_TYPE")
	public Integer getPersonType() {
		return this.personType;
	}

	public void setPersonType(Integer personType) {
		this.personType = personType;
	}

	@Column(name = "PROJECT_ID")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "COURSE_ID")
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	@Column(name = "SIGN_TYPE")
	public Integer getSignType() {
		return this.signType;
	}

	public void setSignType(Integer signType) {
		this.signType = signType;
	}

	@Column(name = "CHECK_TYPE")
	public Integer getCheckType() {
		return this.checkType;
	}

	public void setCheckType(Integer checkType) {
		this.checkType = checkType;
	}

	@Column(name = "CHECK_STATUS")
	public Integer getCheckStatus() {
		return this.checkStatus;
	}

	public void setCheckStatus(Integer checkStatus) {
		this.checkStatus = checkStatus;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SCAN_TIME", length = 19)
	public Date getScanTime() {
		return scanTime;
	}

	public void setScanTime(Date scanTime) {
		this.scanTime = scanTime;
	}

	@Column(name = "MINUTE_NUMBER")
	public Integer getMinuteNumber() {
		return minuteNumber;
	}

	public void setMinuteNumber(Integer minuteNumber) {
		this.minuteNumber = minuteNumber;
	}

	@Column(name = "HOUR_NUMBER", precision = 22, scale = 0)
	public Double getHourNumber() {
		return this.hourNumber;
	}

	public void setHourNumber(Double hourNumber) {
		this.hourNumber = hourNumber;
	}

	@Column(name = "HOUR_STATUS")
	public Integer getHourStatus() {
		return this.hourStatus;
	}

	public void setHourStatus(Integer hourStatus) {
		this.hourStatus = hourStatus;
	}

	@Column(name = "TEST_SCORE")
	public Integer getTestScore() {
		return this.testScore;
	}

	public void setTestScore(Integer testScore) {
		this.testScore = testScore;
	}

	@Column(name = "TEST_TYPE")
	public Integer getTestType() {
		return this.testType;
	}

	public void setTestType(Integer testType) {
		this.testType = testType;
	}

	@Column(name = "TEST_STATUS")
	public Integer getTestStatus() {
		return this.testStatus;
	}

	public void setTestStatus(Integer testStatus) {
		this.testStatus = testStatus;
	}

	@Column(name = "EVA_STATUS")
	public Integer getEvaStatus() {
		return this.evaStatus;
	}

	public void setEvaStatus(Integer evaStatus) {
		this.evaStatus = evaStatus;
	}

	@Column(name = "PASS_STATUS")
	public Integer getPassStatus() {
		return this.passStatus;
	}

	public void setPassStatus(Integer passStatus) {
		this.passStatus = passStatus;
	}

	@Column(name = "NO_PASS_REASON")
	public String getNoPassReason() {
		return this.noPassReason;
	}

	public void setNoPassReason(String noPassReason) {
		this.noPassReason = noPassReason;
	}
	
	
	@Column(name = "IS_INFORM")
	public Integer getIsInform() {
		return isInform;
	}

	public void setIsInform(Integer isInform) {
		this.isInform = isInform;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
