package com.entity;

// Generated 2020-9-4 16:54:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SjDicCompilerType generated by hbm2java
 */
@Entity
@Table(name = "SJ_DIC_COMPILER_TYPE", catalog = "sjtu_train")
public class DicCompilerType implements java.io.Serializable {

	private Integer id;
	private String name;
	private String compilerTypeDesc;
	private Date createTime;
	private Date updateTime;

	public DicCompilerType() {
	}

	public DicCompilerType(String name, String compilerTypeDesc,
			Date createTime, Date updateTime) {
		this.name = name;
		this.compilerTypeDesc = compilerTypeDesc;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "COMPILER_TYPE_DESC")
	public String getCompilerTypeDesc() {
		return this.compilerTypeDesc;
	}

	public void setCompilerTypeDesc(String compilerTypeDesc) {
		this.compilerTypeDesc = compilerTypeDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
