package com.entity;

// Generated 2020-9-4 16:54:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SjDicCareer generated by hbm2java
 */
@Entity
@Table(name = "SJ_DIC_CAREER", catalog = "sast_train")
public class DicCareer implements java.io.Serializable {

	private Integer id;
	private String name;
	private String careerDesc;
	private Date createTime;
	private Date updateTime;

	public DicCareer() {
	}

	public DicCareer(String name, String careerDesc, Date createTime,
			Date updateTime) {
		this.name = name;
		this.careerDesc = careerDesc;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CAREER_DESC")
	public String getCareerDesc() {
		return this.careerDesc;
	}

	public void setCareerDesc(String careerDesc) {
		this.careerDesc = careerDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
