package com.entity;

// Generated 2020-9-4 16:54:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SjDicTeacherType generated by hbm2java
 */
@Entity
@Table(name = "SJ_DIC_TEACHER_TYPE", catalog = "sast_train")
public class DicTeacherType implements java.io.Serializable {

	private Integer id;
	private String name;
	private String teacherTypeDesc;
	private Date createTime;
	private Date updateTime;

	public DicTeacherType() {
	}

	public DicTeacherType(String name, String teacherTypeDesc,
			Date createTime, Date updateTime) {
		this.name = name;
		this.teacherTypeDesc = teacherTypeDesc;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TEACHER_TYPE_DESC")
	public String getTeacherTypeDesc() {
		return this.teacherTypeDesc;
	}

	public void setTeacherTypeDesc(String teacherTypeDesc) {
		this.teacherTypeDesc = teacherTypeDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
