package com.entity;

// Generated 2020-7-27 9:52:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SjEvaluateQuestion generated by hbm2java
 */
@Entity
@Table(name = "SJ_EVALUATE_QUESTION", catalog = "sast_train")
public class EvaluateQuestion implements java.io.Serializable {

	private Integer id;
	private Integer libId;
	private String seri;
	private Integer questionOrder;
	private Integer questionType;
	private String content;
	private String optionIds;
	private Integer del;
	private Date createTime;
	private Date updateTime;

	public EvaluateQuestion() {
	}
	
	public EvaluateQuestion(Integer id, Integer libId, String seri,Integer questionOrder,
			Integer questionType, String content, String optionIds,
			Integer del, Date createTime, Date updateTime) {
		this.id = id;
		this.libId = libId;
		this.seri = seri;
		this.questionOrder = questionOrder;
		this.questionType = questionType;
		this.content = content;
		this.optionIds = optionIds;
		this.del = del;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "LIB_ID")
	public Integer getLibId() {
		return this.libId;
	}

	public void setLibId(Integer libId) {
		this.libId = libId;
	}

	@Column(name = "SERI")
	public String getSeri() {
		return this.seri;
	}

	public void setSeri(String seri) {
		this.seri = seri;
	}
	
	@Column(name = "QUESTION_ORDER")
	public Integer getQuestionOrder() {
		return questionOrder;
	}

	public void setQuestionOrder(Integer questionOrder) {
		this.questionOrder = questionOrder;
	}
	
	@Column(name = "QUESTION_TYPE")
	public Integer getQuestionType() {
		return this.questionType;
	}

	public void setQuestionType(Integer questionType) {
		this.questionType = questionType;
	}

	@Column(name = "CONTENT")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "OPTION_IDS")
	public String getOptionIds() {
		return this.optionIds;
	}

	public void setOptionIds(String optionIds) {
		this.optionIds = optionIds;
	}

	@Column(name = "DEL")
	public Integer getDel() {
		return this.del;
	}

	public void setDel(Integer del) {
		this.del = del;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
