package com.entity;

// Generated 2020-9-4 16:54:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SjHourPeriodTeacher generated by hbm2java
 */
@Entity
@Table(name = "SJ_HOUR_PERIOD_TEACHER", catalog = "sast_train")
public class HourPeriodTeacher implements java.io.Serializable {

	private Integer id;
	private Integer hourPeriodId;
	private String account;
	private Double hourTotal;
	private Double hourSum;
	private Date createTime;
	private Date updateTime;

	public HourPeriodTeacher() {
	}

	public HourPeriodTeacher(Integer hourPeriodId, String account,
			Double hourTotal, Double hourSum, Date createTime, Date updateTime) {
		this.hourPeriodId = hourPeriodId;
		this.account = account;
		this.hourTotal = hourTotal;
		this.hourSum = hourSum;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "HOUR_PERIOD_ID")
	public Integer getHourPeriodId() {
		return this.hourPeriodId;
	}

	public void setHourPeriodId(Integer hourPeriodId) {
		this.hourPeriodId = hourPeriodId;
	}

	@Column(name = "ACCOUNT")
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "HOUR_TOTAL", precision = 22, scale = 0)
	public Double getHourTotal() {
		return this.hourTotal;
	}

	public void setHourTotal(Double hourTotal) {
		this.hourTotal = hourTotal;
	}

	@Column(name = "HOUR_SUM", precision = 22, scale = 0)
	public Double getHourSum() {
		return this.hourSum;
	}

	public void setHourSum(Double hourSum) {
		this.hourSum = hourSum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
