package com.entity;

// Generated 2020-7-22 10:29:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SjOrgani generated by hbm2java
 */
@Entity
@Table(name = "SJ_ORGANI", catalog = "sjtu_train", uniqueConstraints = @UniqueConstraint(columnNames = "ORGANI_CODE"))
public class Organi implements java.io.Serializable {

	private Integer id;
	private String organiCode;
	private String organiName;
	private String parentOrganiCode;
	private Integer independent;
	private Integer disabled;
	private Integer organiPlusId;
	private Date createTime;
	private Date updateTime;

	public Organi() {
	}

	public Organi(String organiCode, String organiName,
			String parentOrganiCode, Integer independent, Integer disabled,
			Integer organiPlusId,Date createTime, Date updateTime) {
		this.organiCode = organiCode;
		this.organiName = organiName;
		this.parentOrganiCode = parentOrganiCode;
		this.independent = independent;
		this.disabled = disabled;
		this.organiPlusId = organiPlusId;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ORGANI_CODE", unique = true)
	public String getOrganiCode() {
		return this.organiCode;
	}

	public void setOrganiCode(String organiCode) {
		this.organiCode = organiCode;
	}

	@Column(name = "ORGANI_NAME")
	public String getOrganiName() {
		return this.organiName;
	}

	public void setOrganiName(String organiName) {
		this.organiName = organiName;
	}

	@Column(name = "PARENT_ORGANI_CODE")
	public String getParentOrganiCode() {
		return this.parentOrganiCode;
	}

	public void setParentOrganiCode(String parentOrganiCode) {
		this.parentOrganiCode = parentOrganiCode;
	}

	@Column(name = "INDEPENDENT")
	public Integer getIndependent() {
		return this.independent;
	}

	public void setIndependent(Integer independent) {
		this.independent = independent;
	}

	@Column(name = "DISABLED")
	public Integer getDisabled() {
		return this.disabled;
	}

	public void setDisabled(Integer disabled) {
		this.disabled = disabled;
	}
	
	@Column(name = "ORGANI_PLUS_ID")
	public Integer getOrganiPlusId() {
		return organiPlusId;
	}

	public void setOrganiPlusId(Integer organiPlusId) {
		this.organiPlusId = organiPlusId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
