package com.entity;

// Generated 2020-7-22 10:29:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SjOrganiPlus generated by hbm2java
 */
@Entity
@Table(name = "SJ_ORGANI_PLUS", catalog = "sjtu_train", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
public class OrganiPlus implements java.io.Serializable {

	private Integer id;
	private String name;
	private String organiPlusDesc;
	private String organiCodes;
	private Date createTime;
	private Date updateTime;

	public OrganiPlus() {
	}

	public OrganiPlus(String name, String organiPlusDesc, String organiCodes,
			Date createTime, Date updateTime) {
		this.name = name;
		this.organiPlusDesc = organiPlusDesc;
		this.organiCodes = organiCodes;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", unique = true)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ORGANI_PLUS_DESC")
	public String getOrganiPlusDesc() {
		return organiPlusDesc;
	}

	public void setOrganiPlusDesc(String organiPlusDesc) {
		this.organiPlusDesc = organiPlusDesc;
	}

	@Column(name = "ORGANI_CODES")
	public String getOrganiCodes() {
		return this.organiCodes;
	}

	public void setOrganiCodes(String organiCodes) {
		this.organiCodes = organiCodes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
