package com.entity;

// Generated 2020-7-22 10:29:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SjProjectPassRule generated by hbm2java
 */
@Entity
@Table(name = "SJ_PROJECT_PASS_RULE", catalog = "sjtu_train")
public class ProjectPassRule implements java.io.Serializable {

	private Integer id;
	private Integer projectId;
	private Integer courseSingleOrTogether;
	private Integer courseNumberOrHour;
	private Integer test;
	private Date testStartTime;
	private Date testEndTime;
	private Integer evaluate;
	private Date evaluateStartTime;
	private Date evaluateEndTime;
	private Integer report;
	private Date reportStartTime;
	private Date reportEndTime;
	private Integer requireNumber;
	private Integer optionalNumber;
	private Integer requireHour;
	private Integer optionalHour;
	private Date createTime;
	private Date updateTime;

	public ProjectPassRule() {
	}

	public ProjectPassRule(Integer projectId, Integer courseSingleOrTogether,
			Integer courseNumberOrHour, Integer test, Date testStartTime,Date testEndTime,
			Integer evaluate,Date evaluateStartTime,Date evaluateEndTime,
			Integer report, Date reportStartTime,Date reportEndTime,
			Integer requireNumber, Integer optionalNumber,
			Integer requireHour, Integer optionalHour, Date createTime,Date updateTime) {
		this.projectId = projectId;
		this.courseSingleOrTogether = courseSingleOrTogether;
		this.courseNumberOrHour = courseNumberOrHour;
		this.test = test;
		this.testStartTime = testStartTime;
		this.testEndTime = testEndTime;
		this.evaluate = evaluate;
		this.evaluateStartTime = evaluateStartTime;
		this.evaluateEndTime = evaluateEndTime;
		this.report = report;
		this.reportStartTime = reportStartTime;
		this.reportEndTime = reportEndTime;
		this.requireNumber = requireNumber;
		this.optionalNumber = optionalNumber;
		this.requireHour = requireHour;
		this.optionalHour = optionalHour;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "PROJECT_ID")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "COURSE_SINGLE_OR_TOGETHER")
	public Integer getCourseSingleOrTogether() {
		return this.courseSingleOrTogether;
	}

	public void setCourseSingleOrTogether(Integer courseSingleOrTogether) {
		this.courseSingleOrTogether = courseSingleOrTogether;
	}

	@Column(name = "COURSE_NUMBER_OR_HOUR")
	public Integer getCourseNumberOrHour() {
		return this.courseNumberOrHour;
	}

	public void setCourseNumberOrHour(Integer courseNumberOrHour) {
		this.courseNumberOrHour = courseNumberOrHour;
	}

	@Column(name = "TEST")
	public Integer getTest() {
		return this.test;
	}

	public void setTest(Integer test) {
		this.test = test;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TEST_START_TIME", length = 19)
	public Date getTestStartTime() {
		return testStartTime;
	}

	public void setTestStartTime(Date testStartTime) {
		this.testStartTime = testStartTime;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TEST_END_TIME", length = 19)
	public Date getTestEndTime() {
		return testEndTime;
	}

	public void setTestEndTime(Date testEndTime) {
		this.testEndTime = testEndTime;
	}

	@Column(name = "EVALUATE")
	public Integer getEvaluate() {
		return this.evaluate;
	}

	public void setEvaluate(Integer evaluate) {
		this.evaluate = evaluate;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EVALUATE_START_TIME", length = 19)
	public Date getEvaluateStartTime() {
		return evaluateStartTime;
	}

	public void setEvaluateStartTime(Date evaluateStartTime) {
		this.evaluateStartTime = evaluateStartTime;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EVALUATE_END_TIME", length = 19)
	public Date getEvaluateEndTime() {
		return evaluateEndTime;
	}

	public void setEvaluateEndTime(Date evaluateEndTime) {
		this.evaluateEndTime = evaluateEndTime;
	}

	@Column(name = "REPORT")
	public Integer getReport() {
		return this.report;
	}

	public void setReport(Integer report) {
		this.report = report;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REPORT_START_TIME", length = 19)
	public Date getReportStartTime() {
		return reportStartTime;
	}

	public void setReportStartTime(Date reportStartTime) {
		this.reportStartTime = reportStartTime;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REPORT_END_TIME", length = 19)
	public Date getReportEndTime() {
		return reportEndTime;
	}

	public void setReportEndTime(Date reportEndTime) {
		this.reportEndTime = reportEndTime;
	}

	@Column(name = "REQUIRE_NUMBER")
	public Integer getRequireNumber() {
		return this.requireNumber;
	}

	public void setRequireNumber(Integer requireNumber) {
		this.requireNumber = requireNumber;
	}

	@Column(name = "OPTIONAL_NUMBER")
	public Integer getOptionalNumber() {
		return this.optionalNumber;
	}

	public void setOptionalNumber(Integer optionalNumber) {
		this.optionalNumber = optionalNumber;
	}

	@Column(name = "REQUIRE_HOUR")
	public Integer getRequireHour() {
		return this.requireHour;
	}

	public void setRequireHour(Integer requireHour) {
		this.requireHour = requireHour;
	}

	@Column(name = "OPTIONAL_HOUR")
	public Integer getOptionalHour() {
		return this.optionalHour;
	}

	public void setOptionalHour(Integer optionalHour) {
		this.optionalHour = optionalHour;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
