package com.entity;

// Generated 2020-7-28 13:41:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SjProjectOutSchool generated by hbm2java
 */
@Entity
@Table(name = "SJ_PROJECT_OUT_SCHOOL", catalog = "sjtu_train")
public class ProjectOutSchool implements java.io.Serializable {

	private Integer id;
	private Integer projectId;
	private String organizerName;
	private String suborganizerName;
	private String certOrganizerName;
	private Date createTime;
	private Date updateTime;

	public ProjectOutSchool() {
	}

	public ProjectOutSchool(Integer projectId,String organizerName, String suborganizerName, 
			String certOrganizerName, Date createTime, Date updateTime) {
		this.projectId = projectId;
		this.organizerName = organizerName;
		this.suborganizerName = suborganizerName;
		this.certOrganizerName = certOrganizerName;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "projectId")
	public Integer getProjectId() {
		return projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}
	
	@Column(name = "organizerName")
	public String getOrganizerName() {
		return organizerName;
	}

	public void setOrganizerName(String organizerName) {
		this.organizerName = organizerName;
	}
	
	@Column(name = "suborganizerName")
	public String getSuborganizerName() {
		return suborganizerName;
	}

	public void setSuborganizerName(String suborganizerName) {
		this.suborganizerName = suborganizerName;
	}
	
	@Column(name = "certOrganizerName")
	public String getCertOrganizerName() {
		return certOrganizerName;
	}

	public void setCertOrganizerName(String certOrganizerName) {
		this.certOrganizerName = certOrganizerName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
