package com.entity;

// Generated 2020-7-28 13:41:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GNJXK generated by hbm2java
 */
@Entity
@Table(name = "GNJXK", catalog = "sast_train")
public class ProjectGnjxk implements java.io.Serializable {

	private String id;
	private Integer projectId;
	private String account;
	private String gh;
	private String name;
	private String organiCode;
	private String organiName;
	private String jxnys;
	private String jxnyz;
	private String jxkt;
	private String jxdw;
	private String cbdw;
	private String fzbm;
	private String zsyxq;
	private String zsmc;
	private String xxfsm;
	private String xs;
	private String jxbx;
	private String delMark;
	private Date createTime;
	private Date updateTime;

	public ProjectGnjxk() {
	}

	public ProjectGnjxk(Integer projectId,String account,String gh,String name,String organiCode,
			String organiName,String jxnys, String jxnyz,String jxkt,String jxdw, 
			String cbdw,String fzbm,String zsyxq,String zsmc,String xxfsm,String xs,
			String jxbx,String delMark,Date createTime, Date updateTime) {
		this.projectId = projectId;
		this.account = account;
		this.gh = gh;
		this.name = name;
		this.organiCode = organiCode;
		this.organiName = organiName;
		this.jxnys = jxnys;
		this.jxnyz = jxnyz;
		this.jxkt = jxkt;
		this.jxdw = jxdw;
		this.cbdw = cbdw;
		this.fzbm = fzbm;
		this.zsyxq = zsyxq;
		this.zsmc = zsmc;
		this.xxfsm = xxfsm;
		this.xs = xs;
		this.jxbx = jxbx;
		this.delMark = delMark;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}
	
	@Id
	@Column(name = "id", unique = true, nullable = false, length = 64)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	@Column(name = "projectId")
	public Integer getProjectId() {
		return projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}
	
	@Column(name = "account")
	public String getAccount() {
		return account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "gh")
	public String getGh() {
		return gh;
	}

	public void setGh(String gh) {
		this.gh = gh;
	}
	
	@Column(name = "name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "organiCode")
	public String getOrganiCode() {
		return organiCode;
	}

	public void setOrganiCode(String organiCode) {
		this.organiCode = organiCode;
	}
	
	@Column(name = "organiName")
	public String getOrganiName() {
		return organiName;
	}

	public void setOrganiName(String organiName) {
		this.organiName = organiName;
	}

	@Column(name = "jxnys")
	public String getJxnys() {
		return jxnys;
	}

	public void setJxnys(String jxnys) {
		this.jxnys = jxnys;
	}
	
	@Column(name = "jxnyz")
	public String getJxnyz() {
		return jxnyz;
	}
	
	public void setJxnyz(String jxnyz) {
		this.jxnyz = jxnyz;
	}
	
	@Column(name = "jxkt")
	public String getJxkt() {
		return jxkt;
	}

	public void setJxkt(String jxkt) {
		this.jxkt = jxkt;
	}
	
	@Column(name = "jxdw")
	public String getJxdw() {
		return jxdw;
	}

	public void setJxdw(String jxdw) {
		this.jxdw = jxdw;
	}
	
	@Column(name = "cbdw")
	public String getCbdw() {
		return cbdw;
	}

	public void setCbdw(String cbdw) {
		this.cbdw = cbdw;
	}
	
	@Column(name = "fzbm")
	public String getFzbm() {
		return fzbm;
	}

	public void setFzbm(String fzbm) {
		this.fzbm = fzbm;
	}
	
	@Column(name = "zsyxq")
	public String getZsyxq() {
		return zsyxq;
	}

	public void setZsyxq(String zsyxq) {
		this.zsyxq = zsyxq;
	}
	
	@Column(name = "zsmc")
	public String getZsmc() {
		return zsmc;
	}

	public void setZsmc(String zsmc) {
		this.zsmc = zsmc;
	}
	
	@Column(name = "xxfsm")
	public String getXxfsm() {
		return xxfsm;
	}

	public void setXxfsm(String xxfsm) {
		this.xxfsm = xxfsm;
	}
	
	@Column(name = "xs")
	public String getXs() {
		return xs;
	}

	public void setXs(String xs) {
		this.xs = xs;
	}
	
	@Column(name = "jxbx")
	public String getJxbx() {
		return jxbx;
	}

	public void setJxbx(String jxbx) {
		this.jxbx = jxbx;
	}
	
	@Column(name = "del_mark")
	public String getDelMark() {
		return delMark;
	}

	public void setDelMark(String delMark) {
		this.delMark = delMark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
