package com.entity;

// Generated 2020-8-7 16:35:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SjProjectAlloc generated by hbm2java
 */
@Entity
@Table(name = "SJ_PROJECT_ALLOC", catalog = "sast_train")
public class ProjectAlloc implements java.io.Serializable {

	private Integer id;
	private Integer projectId;
	private String organiCode;
	private Integer number;
	private String signPosPersons;
	private String signPersonNames;
	private Date createTime;
	private Date updateTime;

	public ProjectAlloc() {
	}

	public ProjectAlloc(Integer projectId, String organiCode, Integer number,
			String signPosPersons,String signPersonNames, Date createTime, Date updateTime) {
		this.projectId = projectId;
		this.organiCode = organiCode;
		this.number = number;
		this.signPosPersons = signPosPersons;
		this.signPersonNames = signPersonNames;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "PROJECT_ID")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "ORGANI_CODE")
	public String getOrganiCode() {
		return organiCode;
	}

	public void setOrganiCode(String organiCode) {
		this.organiCode = organiCode;
	}

	@Column(name = "NUMBER")
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	@Column(name = "SIGN_POS_PERSONS")
	public String getSignPosPersons() {
		return this.signPosPersons;
	}

	public void setSignPosPersons(String signPosPersons) {
		this.signPosPersons = signPosPersons;
	}
	
	@Column(name = "SIGN_PERSON_NAMES")
	public String getSignPersonNames() {
		return signPersonNames;
	}

	public void setSignPersonNames(String signPersonNames) {
		this.signPersonNames = signPersonNames;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
