package com.entity;

// Generated 2020-8-19 10:58:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SjProjectArchive generated by hbm2java
 */
@Entity
@Table(name = "SJ_PROJECT_ARCHIVE", catalog = "sjtu_train")
public class ProjectArchive implements java.io.Serializable {

	private Integer id;
	private String organiCode;
	private String createBy;
	private Integer projectId;
	private String archiveName;
	private String archiveDesc;
	private String projectArchivePath;
	private Integer openForTrainee;
	private Date openExpireTime;
	private String selfType;
	private Integer openForOrganizer;
	private Date organizerExpireTime;
	private Date createTime;
	private Date updateTime;

	public ProjectArchive() {
	}

	public ProjectArchive(String organiCode, String createBy,
			Integer projectId, String archiveName, String archiveDesc,
			String projectArchivePath, Integer openForTrainee,
			Date openExpireTime, String selfType, Integer openForOrganizer,Date organizerExpireTime,
			Date createTime,Date updateTime) {
		this.organiCode = organiCode;
		this.createBy = createBy;
		this.projectId = projectId;
		this.archiveName = archiveName;
		this.archiveDesc = archiveDesc;
		this.projectArchivePath = projectArchivePath;
		this.openForTrainee = openForTrainee;
		this.openExpireTime = openExpireTime;
		this.selfType = selfType;
		this.openForOrganizer = openForOrganizer;
		this.organizerExpireTime = organizerExpireTime;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ORGANI_CODE")
	public String getOrganiCode() {
		return this.organiCode;
	}

	public void setOrganiCode(String organiCode) {
		this.organiCode = organiCode;
	}
	
	@Column(name = "CREATE_BY")
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Column(name = "PROJECT_ID")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "ARCHIVE_NAME")
	public String getArchiveName() {
		return this.archiveName;
	}

	public void setArchiveName(String archiveName) {
		this.archiveName = archiveName;
	}

	@Column(name = "ARCHIVE_DESC")
	public String getArchiveDesc() {
		return this.archiveDesc;
	}

	public void setArchiveDesc(String archiveDesc) {
		this.archiveDesc = archiveDesc;
	}

	@Column(name = "PROJECT_ARCHIVE_PATH")
	public String getProjectArchivePath() {
		return this.projectArchivePath;
	}

	public void setProjectArchivePath(String projectArchivePath) {
		this.projectArchivePath = projectArchivePath;
	}

	@Column(name = "OPEN_FOR_TRAINEE")
	public Integer getOpenForTrainee() {
		return this.openForTrainee;
	}

	public void setOpenForTrainee(Integer openForTrainee) {
		this.openForTrainee = openForTrainee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPEN_EXPIRE_TIME", length = 19)
	public Date getOpenExpireTime() {
		return this.openExpireTime;
	}

	public void setOpenExpireTime(Date openExpireTime) {
		this.openExpireTime = openExpireTime;
	}

	@Column(name = "SELF_TYPE")
	public String getSelfType() {
		return this.selfType;
	}

	public void setSelfType(String selfType) {
		this.selfType = selfType;
	}
	
	@Column(name = "OPEN_FOR_ORGANIZER")
	public Integer getOpenForOrganizer() {
		return openForOrganizer;
	}

	public void setOpenForOrganizer(Integer openForOrganizer) {
		this.openForOrganizer = openForOrganizer;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ORGANIZER_EXPIRE_TIME", length = 19)
	public Date getOrganizerExpireTime() {
		return organizerExpireTime;
	}

	public void setOrganizerExpireTime(Date organizerExpireTime) {
		this.organizerExpireTime = organizerExpireTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
