package com.entity;

// Generated 2020-7-22 10:29:49 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * SjProjectCertificate generated by hbm2java
 */
@Entity
@Table(name = "SJ_PROJECT_CERTIFICATE", catalog = "sast_train")
public class ProjectCertificate implements java.io.Serializable {

    private Integer id;
    private String account;
    private String certifiNo;
    private Integer personType;
    private Integer projectId;
    private String certificateName;
    private String certificatePath;
    private Date createTime;
    private Date updateTime;

    public ProjectCertificate() {
    }

    public ProjectCertificate(String account, String certifiNo, Integer personType,
                              Integer projectId, String certificateName, String certificatePath, Date createTime,
                              Date updateTime) {
        this.account = account;
        this.certifiNo = certifiNo;
        this.personType = personType;
        this.projectId = projectId;
        this.certificateName = certificateName;
        this.certificatePath = certificatePath;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "ACCOUNT")
    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    @Column(name = "CERTIFI_NO")
    public String getCertifiNo() {
        return certifiNo;
    }

    public void setCertifiNo(String certifiNo) {
        this.certifiNo = certifiNo;
    }

    @Column(name = "PERSON_TYPE")
    public Integer getPersonType() {
        return personType;
    }

    public void setPersonType(Integer personType) {
        this.personType = personType;
    }

    @Column(name = "PROJECT_ID")
    public Integer getProjectId() {
        return this.projectId;
    }

    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    @Column(name = "CERTIFICATE_NAME")
    public String getCertificateName() {
        return this.certificateName;
    }

    public void setCertificateName(String certificateName) {
        this.certificateName = certificateName;
    }

    @Column(name = "CERTIFICATE_PATH")
    public String getCertificatePath() {
        return this.certificatePath;
    }

    public void setCertificatePath(String certificatePath) {
        this.certificatePath = certificatePath;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_TIME", length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_TIME", length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
