package com.entity;

// Generated 2020-7-28 13:41:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SjProjectShare generated by hbm2java
 */
@Entity
@Table(name = "SJ_PROJECT_SHARE", catalog = "sast_train")
public class ProjectShare implements java.io.Serializable {

	private Integer id;
	private String fromAccount;
	private String toAccount;
	private Integer fromProjectId;
	private Integer toProjectId;
	private String fromCourseIds;
	private String toCourseIds;
	private Integer shareResult;
	private String shareReason;
	private Date createTime;
	private Date updateTime;

	public ProjectShare() {
	}

	public ProjectShare(String fromAccount, String toAccount, Integer fromProjectId,Integer toProjectId, 
			String fromCourseIds,String toCourseIds,Integer shareResult,
			String shareReason, Date createTime, Date updateTime) {
		this.fromAccount = fromAccount;
		this.toAccount = toAccount;
		this.fromProjectId = fromProjectId;
		this.toProjectId = toProjectId;
		this.fromCourseIds = fromCourseIds;
		this.toCourseIds = toCourseIds;
		this.shareResult = shareResult;
		this.shareReason = shareReason;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "FROM_ACCOUNT")
	public String getFromAccount() {
		return fromAccount;
	}

	public void setFromAccount(String fromAccount) {
		this.fromAccount = fromAccount;
	}
	
	@Column(name = "TO_ACCOUNT")
	public String getToAccount() {
		return toAccount;
	}

	public void setToAccount(String toAccount) {
		this.toAccount = toAccount;
	}
	
	@Column(name = "FROM_PROJECT_ID")
	public Integer getFromProjectId() {
		return fromProjectId;
	}

	public void setFromProjectId(Integer fromProjectId) {
		this.fromProjectId = fromProjectId;
	}
	
	@Column(name = "TO_PROJECT_ID")
	public Integer getToProjectId() {
		return toProjectId;
	}

	public void setToProjectId(Integer toProjectId) {
		this.toProjectId = toProjectId;
	}
	
	@Column(name = "FROM_COURSE_IDS")
	public String getFromCourseIds() {
		return fromCourseIds;
	}

	public void setFromCourseIds(String fromCourseIds) {
		this.fromCourseIds = fromCourseIds;
	}
	
	@Column(name = "TO_COURSE_IDS")
	public String getToCourseIds() {
		return toCourseIds;
	}

	public void setToCourseIds(String toCourseIds) {
		this.toCourseIds = toCourseIds;
	}
	
	@Column(name = "SHARE_RESULT")
	public Integer getShareResult() {
		return shareResult;
	}

	public void setShareResult(Integer shareResult) {
		this.shareResult = shareResult;
	}
	
	@Column(name = "SHARE_REASON")
	public String getShareReason() {
		return shareReason;
	}

	public void setShareReason(String shareReason) {
		this.shareReason = shareReason;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
