package com.entity;

// Generated 2020-7-22 10:29:49 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * SjProjectTrainType generated by hbm2java
 */
@Entity
@Table(name = "SJ_PROJECT_OUTTRAIN_TYPE", catalog = "sjtu_train")
public class ProjectOutTrainType implements java.io.Serializable {

	private Integer id;
	private String name;


	private String outTrainTypeDesc;
	private String imagePath;
	private String certCode;
	private Integer del;
	private Date createTime;
	private Date updateTime;

	public ProjectOutTrainType() {
	}

	public ProjectOutTrainType(String name, String outTrainTypeDesc, String certCode,
                               String imagePath, Integer del, Date createTime, Date updateTime) {
		this.name = name;
		this.outTrainTypeDesc = outTrainTypeDesc;
		this.imagePath = imagePath;
		this.certCode = certCode;
		this.del = del;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "OUTTRAIN_TYPE_DESC")
	public String getOutTrainTypeDesc() {
		return this.outTrainTypeDesc;
	}

	public void setOutTrainTypeDesc(String outTrainTypeDesc) {
		this.outTrainTypeDesc = outTrainTypeDesc;
	}


	@Column(name = "IMAGE_PATH")
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}
	
	@Column(name = "CERT_CODE")
	public String getCertCode() {
		return certCode;
	}

	public void setCertCode(String certCode) {
		this.certCode = certCode;
	}

	@Column(name = "DEL")
	public Integer getDel() {
		return this.del;
	}

	public void setDel(Integer del) {
		this.del = del;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
