package com.entity;

// Generated 2020-9-4 16:54:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SjResultHealthQrcode generated by hbm2java
 */
@Entity
@Table(name = "SJ_RESULT_HEALTH_QRCODE", catalog = "sast_train")
public class ResultHealthQrcode implements java.io.Serializable {

	private Integer id;
	private String account;
	private String certifiNo;
	private Integer personType;
	private Integer projectId;
	private String healthQrcodePath;
	private Date createTime;
	private Date updateTime;

	public ResultHealthQrcode() {
	}

	public ResultHealthQrcode(String account, String certifiNo, Integer personType,
			Integer projectId, String healthQrcodePath, Date createTime,
			Date updateTime) {
		this.account = account;
		this.certifiNo = certifiNo;
		this.personType = personType;
		this.projectId = projectId;
		this.healthQrcodePath = healthQrcodePath;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ACCOUNT")
	public String getAccount() {
		return account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "CERTIFI_NO")
	public String getCertifiNo() {
		return certifiNo;
	}

	public void setCertifiNo(String certifiNo) {
		this.certifiNo = certifiNo;
	}
	
	@Column(name = "PERSON_TYPE")
	public Integer getPersonType() {
		return personType;
	}

	public void setPersonType(Integer personType) {
		this.personType = personType;
	}

	@Column(name = "PROJECT_ID")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "HEALTH_QRCODE_PATH")
	public String getHealthQrcodePath() {
		return this.healthQrcodePath;
	}

	public void setHealthQrcodePath(String healthQrcodePath) {
		this.healthQrcodePath = healthQrcodePath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
