package com.entity;

// Generated 2020-7-22 10:29:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SjStudentInfo generated by hbm2java
 */
@Entity
@Table(name = "SJ_STUDENT_INFO_SYNC", catalog = "sjtu_train")
public class StudentInfoSync implements java.io.Serializable {

	private Integer id;
	private String organiCode;
	private String organiName;
	private String name;
	private String SNo;
	private String account;
	private String cardNo;
	private String sex;
	private String birthDay;
	private String phone;
	private String email;
	private Date createTime;
	private Date updateTime;
	private String zzqkm;
	private String zzqkmc;
	private String zzmmm;
	private String zzmmmc;
	private String gjm;
	private String gjmc;

	public StudentInfoSync() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ORGANI_CODE")
	public String getOrganiCode() {
		return this.organiCode;
	}

	public void setOrganiCode(String organiCode) {
		this.organiCode = organiCode;
	}

	@Column(name = "ORGANI_NAME")
	public String getOrganiName() {
		return this.organiName;
	}

	public void setOrganiName(String organiName) {
		this.organiName = organiName;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "S_NO")
	public String getSNo() {
		return this.SNo;
	}

	public void setSNo(String SNo) {
		this.SNo = SNo;
	}

	@Column(name = "ACCOUNT")
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}
	
	@Column(name = "CARD_NO")
	public String getCardNo() {
		return cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	@Column(name = "SEX")
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}
	
	@Column(name = "BIRTH_DAY")
	public String getBirthDay() {
		return birthDay;
	}

	public void setBirthDay(String birthDay) {
		this.birthDay = birthDay;
	}
	
	@Column(name = "PHONE")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "EMAIL")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	
	@Column(name = "zzqkm")
	public String getZzqkm() {
		return zzqkm;
	}

	public void setZzqkm(String zzqkm) {
		this.zzqkm = zzqkm;
	}
	
	@Column(name = "zzqkmc")
	public String getZzqkmc() {
		return zzqkmc;
	}

	public void setZzqkmc(String zzqkmc) {
		this.zzqkmc = zzqkmc;
	}
	
	@Column(name = "zzmmm")
	public String getZzmmm() {
		return zzmmm;
	}

	public void setZzmmm(String zzmmm) {
		this.zzmmm = zzmmm;
	}
	
	@Column(name = "zzmmmc")
	public String getZzmmmc() {
		return zzmmmc;
	}

	public void setZzmmmc(String zzmmmc) {
		this.zzmmmc = zzmmmc;
	}
	
	@Column(name = "gjm")
	public String getGjm() {
		return gjm;
	}

	public void setGjm(String gjm) {
		this.gjm = gjm;
	}
	
	@Column(name = "gjmc")
	public String getGjmc() {
		return gjmc;
	}

	public void setGjmc(String gjmc) {
		this.gjmc = gjmc;
	}

}
