package com.entity;

// Generated 2020-7-22 10:29:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SjTestRule generated by hbm2java
 */
@Entity
@Table(name = "SJ_TEST_RULE", catalog = "sast_train")
public class TestRule implements java.io.Serializable {

	private Integer id;
	private String name;
	private String organiCode;
	private String createBy;
	private Integer questionType1Number;
	private Integer questionType1Score;
	private Integer questionType2Number;
	private Integer questionType2Score;
	private Integer questionType3Number;
	private Integer questionType3Score;
	private Integer questionType4Number;
	private Integer questionType4Score;
	private Integer questionType5Number;
	private Integer questionType5Score;
	private Integer outOfOrder;
	private Integer del;
	private Date createTime;
	private Date updateTime;
	private Integer passScore;
	private Integer timeLimit;
	private Integer testRepeat;

	public TestRule() {
	}

	public TestRule(String name, String organiCode, String createBy,
			Integer questionType1Number, Integer questionType1Score,
			Integer questionType2Number, Integer questionType2Score,
			Integer questionType3Number, Integer questionType3Score,
			Integer questionType4Number, Integer questionType4Score,
			Integer questionType5Number, Integer questionType5Score,
			Integer outOfOrder, Integer del, Date createTime, Date updateTime,
			Integer passScore, Integer timeLimit, Integer testRepeat) {
		this.name = name;
		this.organiCode = organiCode;
		this.createBy = createBy;
		this.questionType1Number = questionType1Number;
		this.questionType1Score = questionType1Score;
		this.questionType2Number = questionType2Number;
		this.questionType2Score = questionType2Score;
		this.questionType3Number = questionType3Number;
		this.questionType3Score = questionType3Score;
		this.questionType4Number = questionType4Number;
		this.questionType4Score = questionType4Score;
		this.questionType5Number = questionType5Number;
		this.questionType5Score = questionType5Score;
		this.outOfOrder = outOfOrder;
		this.del = del;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.passScore = passScore;
		this.timeLimit = timeLimit;
		this.testRepeat = testRepeat;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ORGANI_CODE")
	public String getOrganiCode() {
		return this.organiCode;
	}

	public void setOrganiCode(String organiCode) {
		this.organiCode = organiCode;
	}

	@Column(name = "CREATE_BY")
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Column(name = "QUESTION_TYPE_1_NUMBER")
	public Integer getQuestionType1Number() {
		return this.questionType1Number;
	}

	public void setQuestionType1Number(Integer questionType1Number) {
		this.questionType1Number = questionType1Number;
	}

	@Column(name = "QUESTION_TYPE_1_SCORE")
	public Integer getQuestionType1Score() {
		return this.questionType1Score;
	}

	public void setQuestionType1Score(Integer questionType1Score) {
		this.questionType1Score = questionType1Score;
	}

	@Column(name = "QUESTION_TYPE_2_NUMBER")
	public Integer getQuestionType2Number() {
		return this.questionType2Number;
	}

	public void setQuestionType2Number(Integer questionType2Number) {
		this.questionType2Number = questionType2Number;
	}

	@Column(name = "QUESTION_TYPE_2_SCORE")
	public Integer getQuestionType2Score() {
		return this.questionType2Score;
	}

	public void setQuestionType2Score(Integer questionType2Score) {
		this.questionType2Score = questionType2Score;
	}

	@Column(name = "QUESTION_TYPE_3_NUMBER")
	public Integer getQuestionType3Number() {
		return this.questionType3Number;
	}

	public void setQuestionType3Number(Integer questionType3Number) {
		this.questionType3Number = questionType3Number;
	}

	@Column(name = "QUESTION_TYPE_3_SCORE")
	public Integer getQuestionType3Score() {
		return this.questionType3Score;
	}

	public void setQuestionType3Score(Integer questionType3Score) {
		this.questionType3Score = questionType3Score;
	}

	@Column(name = "QUESTION_TYPE_4_NUMBER")
	public Integer getQuestionType4Number() {
		return this.questionType4Number;
	}

	public void setQuestionType4Number(Integer questionType4Number) {
		this.questionType4Number = questionType4Number;
	}

	@Column(name = "QUESTION_TYPE_4_SCORE")
	public Integer getQuestionType4Score() {
		return this.questionType4Score;
	}

	public void setQuestionType4Score(Integer questionType4Score) {
		this.questionType4Score = questionType4Score;
	}

	@Column(name = "QUESTION_TYPE_5_NUMBER")
	public Integer getQuestionType5Number() {
		return this.questionType5Number;
	}

	public void setQuestionType5Number(Integer questionType5Number) {
		this.questionType5Number = questionType5Number;
	}

	@Column(name = "QUESTION_TYPE_5_SCORE")
	public Integer getQuestionType5Score() {
		return this.questionType5Score;
	}

	public void setQuestionType5Score(Integer questionType5Score) {
		this.questionType5Score = questionType5Score;
	}

	@Column(name = "OUT_OF_ORDER")
	public Integer getOutOfOrder() {
		return this.outOfOrder;
	}

	public void setOutOfOrder(Integer outOfOrder) {
		this.outOfOrder = outOfOrder;
	}

	@Column(name = "DEL")
	public Integer getDel() {
		return this.del;
	}

	public void setDel(Integer del) {
		this.del = del;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "PASS_SCORE")
	public Integer getPassScore() {
		return this.passScore;
	}

	public void setPassScore(Integer passScore) {
		this.passScore = passScore;
	}

	@Column(name = "TIME_LIMIT")
	public Integer getTimeLimit() {
		return this.timeLimit;
	}

	public void setTimeLimit(Integer timeLimit) {
		this.timeLimit = timeLimit;
	}

	@Column(name = "TEST_REPEAT")
	public Integer getTestRepeat() {
		return this.testRepeat;
	}

	public void setTestRepeat(Integer testRepeat) {
		this.testRepeat = testRepeat;
	}

}
