package com.entity;

// Generated 2020-7-28 10:36:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SjTestLib generated by hbm2java
 */
@Entity
@Table(name = "SJ_TEST_LIB", catalog = "sjtu_train")
public class TestLib implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer libType;
	private String organiCode;
	private String createBy;
	private String coManagers;
	private Integer del;
	private Integer childNumber;
	private Date createTime;
	private Date updateTime;

	public TestLib() {
	}

	public TestLib(String name, Integer libType, String organiCode,
			String createBy, String coManagers, Integer del,
			Integer childNumber, Date createTime, Date updateTime) {
		this.name = name;
		this.libType = libType;
		this.organiCode = organiCode;
		this.createBy = createBy;
		this.coManagers = coManagers;
		this.del = del;
		this.childNumber = childNumber;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "LIB_TYPE")
	public Integer getLibType() {
		return this.libType;
	}

	public void setLibType(Integer libType) {
		this.libType = libType;
	}

	@Column(name = "ORGANI_CODE")
	public String getOrganiCode() {
		return this.organiCode;
	}

	public void setOrganiCode(String organiCode) {
		this.organiCode = organiCode;
	}

	@Column(name = "CREATE_BY")
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Column(name = "CO_MANAGERS")
	public String getCoManagers() {
		return this.coManagers;
	}

	public void setCoManagers(String coManagers) {
		this.coManagers = coManagers;
	}

	@Column(name = "DEL")
	public Integer getDel() {
		return this.del;
	}

	public void setDel(Integer del) {
		this.del = del;
	}

	@Column(name = "CHILD_NUMBER")
	public Integer getChildNumber() {
		return this.childNumber;
	}

	public void setChildNumber(Integer childNumber) {
		this.childNumber = childNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
