package com.entity;

// Generated 2020-7-27 8:41:28 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SjUserOutSchool generated by hbm2java
 */
@Entity
@Table(name = "SJ_USER_OUT_SCHOOL", catalog = "sast_train")
public class UserOutSchool implements java.io.Serializable {

	private Integer id;
	private String userName;
	private String salt;
	private String password;
	private String realName;
	private Integer certifiType;
	private String certifiNo;
	private String sex;
	private String phone;
	private String email;
	private String workPlace;
	private Integer userCancel;
	private Date loginTime;
	private Date createTime;
	private Date updateTime;

	public UserOutSchool() {
	}

	public UserOutSchool(String userName, String salt, String password,
			String realName, Integer certifiType, String certifiNo,String sex,
			String phone, String email, String workPlace, Integer userCancel,
			Date loginTime,Date createTime, Date updateTime) {
		this.userName = userName;
		this.salt = salt;
		this.password = password;
		this.realName = realName;
		this.certifiType = certifiType;
		this.certifiNo = certifiNo;
		this.sex=sex;
		this.phone = phone;
		this.email = email;
		this.workPlace = workPlace;
		this.userCancel = userCancel;
		this.loginTime = loginTime;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "USER_NAME")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "SALT")
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	@Column(name = "PASSWORD")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "REAL_NAME")
	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	@Column(name = "CERTIFI_TYPE")
	public Integer getCertifiType() {
		return this.certifiType;
	}

	public void setCertifiType(Integer certifiType) {
		this.certifiType = certifiType;
	}

	@Column(name = "CERTIFI_NO")
	public String getCertifiNo() {
		return this.certifiNo;
	}

	public void setCertifiNo(String certifiNo) {
		this.certifiNo = certifiNo;
	}
	
	@Column(name = "SEX")
	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "PHONE")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "EMAIL")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "WORK_PLACE")
	public String getWorkPlace() {
		return this.workPlace;
	}

	public void setWorkPlace(String workPlace) {
		this.workPlace = workPlace;
	}

	@Column(name = "USER_CANCEL")
	public Integer getUserCancel() {
		return this.userCancel;
	}

	public void setUserCancel(Integer userCancel) {
		this.userCancel = userCancel;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LOGIN_TIME", length = 19)
	public Date getLoginTime() {
		return loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
