package com.entity;

// Generated 2020-7-22 10:29:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SjVideo generated by hbm2java
 */
@Entity
@Table(name = "SJ_VIDEO", catalog = "sast_train")
public class Video implements java.io.Serializable {

	private Integer id;
	private Integer libId;
	private String name;
	private String hourLength;
	private String videoFormat;
	private String filePath;
	private Date createTime;
	private Date updateTime;

	public Video() {
	}

	public Video(Integer libId, String name, String hourLength,
			String videoFormat, String filePath, Date createTime,
			Date updateTime) {
		this.libId = libId;
		this.name = name;
		this.hourLength = hourLength;
		this.videoFormat = videoFormat;
		this.filePath = filePath;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "LIB_ID")
	public Integer getLibId() {
		return this.libId;
	}

	public void setLibId(Integer libId) {
		this.libId = libId;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "HOUR_LENGTH")
	public String getHourLength() {
		return this.hourLength;
	}

	public void setHourLength(String hourLength) {
		this.hourLength = hourLength;
	}

	@Column(name = "VIDEO_FORMAT")
	public String getVideoFormat() {
		return this.videoFormat;
	}

	public void setVideoFormat(String videoFormat) {
		this.videoFormat = videoFormat;
	}

	@Column(name = "FILE_PATH")
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
