package com.entity;

// Generated 2020-7-27 8:41:28 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SjVideoLib generated by hbm2java
 */
@Entity
@Table(name = "SJ_VIDEO_LIB", catalog = "sast_train")
public class VideoLib implements java.io.Serializable {

	private Integer id;
	private String name;
	private String libDesc;
	private String organiCode;
	private String createBy;
	private String coManagers;
	private Date createTime;
	private Date updateTime;
	private Integer del;

	public VideoLib() {
	}

	public VideoLib(String name, String libDesc, String organiCode,
			String createBy, String coManagers, Date createTime,
			Date updateTime, Integer del) {
		this.name = name;
		this.libDesc = libDesc;
		this.organiCode = organiCode;
		this.createBy = createBy;
		this.coManagers = coManagers;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.del = del;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "LIB_DESC")
	public String getLibDesc() {
		return this.libDesc;
	}

	public void setLibDesc(String libDesc) {
		this.libDesc = libDesc;
	}

	@Column(name = "ORGANI_CODE")
	public String getOrganiCode() {
		return this.organiCode;
	}

	public void setOrganiCode(String organiCode) {
		this.organiCode = organiCode;
	}

	@Column(name = "CREATE_BY")
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Column(name = "CO_MANAGERS")
	public String getCoManagers() {
		return this.coManagers;
	}

	public void setCoManagers(String coManagers) {
		this.coManagers = coManagers;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "DEL")
	public Integer getDel() {
		return this.del;
	}

	public void setDel(Integer del) {
		this.del = del;
	}

}
